on:
  issue_comment:
    types: [created]

jobs:
  answer-question:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.payload.comment.body === 'Thé ou café ?') {
              github.issues.createComment({
                            issue_number: context.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            body: 'Café'
                          })
            }

